stages:
  - security
  - quality
  - build
  - docker
  - deploy
  - status_deploy

variables:
  IMAGE_NAME: "gitlab.tjpi.jus.br:5050/infraestrutura/agenda-back"
  IMAGE_TAG: "$CI_COMMIT_SHORT_SHA"
  K8S_NAMESPACE: "app-agenda"

default:
  tags:
    - ouvidoria

# --------------------------
# SECURITY (não bloqueante)
# --------------------------
security_scan:
  stage: security
  image: maven:3.9.14-eclipse-temurin-25
  script:
    - ./mvnw -B -DskipTests org.owasp:dependency-check-maven:check || true
  allow_failure: true

# -------------------------
# QUALITY (não bloqueante)
# -------------------------
quality_scan:
  stage: quality
  image: maven:3.9.14-eclipse-temurin-25
  script:
    - ./mvnw -B clean verify || true
  allow_failure: true

# -------------------------
# BUILD (informativo)
# -------------------------
build:
  stage: build
  script:
    - echo "Build realizado dentro do Dockerfile (multi-stage Maven)"

# --------------------------
# DOCKER BUILD (KANIKO)
# --------------------------
docker_build:
  stage: docker
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker

    - echo "{\"auths\":{\"gitlab.tjpi.jus.br:5050\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json

    - |
      /kaniko/executor \
        --context $CI_PROJECT_DIR \
        --dockerfile $CI_PROJECT_DIR/Dockerfile \
        --destination $IMAGE_NAME:$IMAGE_TAG \
        --destination $IMAGE_NAME:latest

# -------------------------
# DEPLOY K8S
# -------------------------
deploy:
  stage: deploy
  image: bitnami/kubectl:latest
  script:

    # Namespace
    - kubectl get ns $K8S_NAMESPACE || kubectl create ns $K8S_NAMESPACE

    # Secret do registry
    - >
      kubectl create secret docker-registry gitlab-registry-secret
      --docker-server=gitlab.tjpi.jus.br:5050
      --docker-username=$CI_REGISTRY_USER
      --docker-password=$CI_REGISTRY_PASSWORD
      --docker-email=devops@tjpi.jus.br
      -n $K8S_NAMESPACE
      --dry-run=client -o yaml | kubectl apply -f -

    # 🔥 Aplicar secrets com envsubst (ANTES de tudo)
    - apt-get update && apt-get install -y gettext
    - envsubst < k8s/postgres-secret.yaml | kubectl apply -n $K8S_NAMESPACE -f -
    #- envsubst < k8s/agenda-back-secret.yaml | kubectl apply -n $K8S_NAMESPACE -f -

    # 🔹 Aplicar resto (SEM secrets)
    - kubectl apply -n $K8S_NAMESPACE -f k8s/postgres-pvc.yaml
    - kubectl apply -n $K8S_NAMESPACE -f k8s/postgres-deployment.yaml
    - kubectl apply -n $K8S_NAMESPACE -f k8s/postgres-service.yaml

    - kubectl apply -n $K8S_NAMESPACE -f k8s/deployment.yaml
    - kubectl apply -n $K8S_NAMESPACE -f k8s/service.yaml

    # Atualizar imagem
    - kubectl set image deployment/agenda-back agenda-back=$IMAGE_NAME:$IMAGE_TAG -n $K8S_NAMESPACE

    # Aguardar rollout
    - kubectl rollout status deployment/agenda-back -n $K8S_NAMESPACE --timeout=180s

  rules:
    - if: '$CI_COMMIT_BRANCH == "dev"'
  needs:
    - docker_build

# -------------------------
# STATUS DO DEPLOY
# -------------------------
status_deploy:
  stage: status_deploy
  image: bitnami/kubectl:latest
  script:
    - kubectl rollout status deployment/agenda-back -n $K8S_NAMESPACE
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev"'