services:
  postgres:
    image: postgres:16-alpine
    container_name: agenda_postgres
    environment:
      POSTGRES_DB: agenda_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: TJPI123
    ports:
      - "5432:5432"
    volumes:
      - agenda_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d agenda_db"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  agenda_postgres_data:
