spring.application.name=agenda-telefonica
spring.config.import=optional:file:.env[.properties]
# Access configuration of database JDBC [cite: 296]
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/agenda_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driverClassName=org.postgresql.Driver

# Update strategy for the database [cite: 8]
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.operations-sorter=alpha
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.display-request-duration=true

# Active Directory (LDAP)
ad.server.url=${AD_SERVER_URL}
ad.domain=${AD_DOMAIN}
ad.upn-suffix=${AD_UPN_SUFFIX}
ad.base-dn=${AD_BASE_DN}
ad.bind-dn=${AD_BIND_DN}
ad.bind-password=${AD_BIND_PASSWORD}