spring.application.name=agenda-telefonica
# Access configuration of database JDBC [cite: 296]
spring.datasource.url=jdbc:postgresql://localhost:5432/agenda_db
spring.datasource.username=postgres
spring.datasource.password=TJPI123
spring.datasource.driverClassName=org.postgresql.Driver

# Update strategy for the database [cite: 8]
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true