apiVersion: apps/v1
kind: Deployment
metadata:
  name: agenda-back
  namespace: app-agenda
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agenda-back
  template:
    metadata:
      labels:
        app: agenda-back
    spec:
      imagePullSecrets:
        - name: gitlab-registry-secret

      containers:
        - name: agenda-back
          image: gitlab.tjpi.jus.br:5050/infraestrutura/agenda-back
          imagePullPolicy: Always

          ports:
            - containerPort: 8080

          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s

            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/agenda_db

            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER

            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD

            # 🔥 evita falha se banco demorar subir
            #- name: SPRING_DATASOURCE_HIKARI_INITIALIZATION_FAIL_TIMEOUT
              #value: "60000"

            #- name: SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT
              #value: "30000"

          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 80
            periodSeconds: 20