apiVersion: apps/v1
kind: Deployment
metadata:
  name: agenda-back
  namespace: app-agenda
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agenda-back
  template:
    metadata:
      labels:
        app: agenda-back
    spec:
      imagePullSecrets:
        - name: gitlab-registry-secret

      containers:
        - name: agenda-back
          image: gitlab.tjpi.jus.br:5050/infraestrutura/agenda-back:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 8080

          envFrom:
            #- configMapRef:
                #name: agenda-back-config
            - secretRef:
                name: agenda-back-secret

          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"

          # 🔹 Melhor para Spring Boot moderno
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 20
            failureThreshold: 3