# Logging em desenvolvimento
logging.level.br.jus.tjpi.agendatelefonica=DEBUG
logging.level.org.springframework.ldap=DEBUG

# Importar propriedades base
spring.config.import=optional:file:.env[.properties]
